-- MySQL Script generated by MySQL Workbench
-- Thu Jul  9 11:19:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dausdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dausdb` ;

-- -----------------------------------------------------
-- Schema dausdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dausdb` DEFAULT CHARACTER SET utf8 ;
USE `dausdb` ;

-- -----------------------------------------------------
-- Table `dausdb`.`PLAYERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dausdb`.`PLAYERS` ;

CREATE TABLE IF NOT EXISTS `dausdb`.`PLAYERS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT 'ANONYMOUS',
  `register_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dausdb`.`DICES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dausdb`.`DICES` ;

CREATE TABLE IF NOT EXISTS `dausdb`.`DICES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dice1` INT NOT NULL,
  `dice2` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dausdb`.`GAMES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dausdb`.`GAMES` ;

CREATE TABLE IF NOT EXISTS `dausdb`.`GAMES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dausdb`.`GAMES_PLAYERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dausdb`.`GAMES_PLAYERS` ;

CREATE TABLE IF NOT EXISTS `dausdb`.`GAMES_PLAYERS` (
  `GAMES_id` INT NOT NULL,
  `PLAYERS_id` INT NOT NULL,
  `won_game` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`GAMES_id`, `PLAYERS_id`),
  INDEX `fk_PLAYERS_has_GAMES_GAMES1_idx` (`GAMES_id` ASC),
  INDEX `fk_PLAYERS_has_GAMES_PLAYERS1_idx` (`PLAYERS_id` ASC),
  CONSTRAINT `fk_PLAYERS_has_GAMES_PLAYERS1`
    FOREIGN KEY (`PLAYERS_id`)
    REFERENCES `dausdb`.`PLAYERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYERS_has_GAMES_GAMES1`
    FOREIGN KEY (`GAMES_id`)
    REFERENCES `dausdb`.`GAMES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dausdb`.`TOSS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dausdb`.`TOSS` ;

CREATE TABLE IF NOT EXISTS `dausdb`.`TOSS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `won_toss` TINYINT(1) NOT NULL DEFAULT 0,
  `gp_GAMES_id` INT NOT NULL,
  `gp_PLAYERS_id` INT NOT NULL,
  `DICES_id` INT NOT NULL,
  PRIMARY KEY (`id`, `gp_GAMES_id`, `gp_PLAYERS_id`, `DICES_id`),
  INDEX `fk_TOSS_GAME_TOSS1_idx` (`DICES_id` ASC),
  INDEX `fk_TOSS_GAME_PLAYERS_GAMES1_idx` (`gp_PLAYERS_id` ASC, `gp_GAMES_id` ASC),
  CONSTRAINT `fk_TOSS_GAME_TOSS1`
    FOREIGN KEY (`DICES_id`)
    REFERENCES `dausdb`.`DICES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TOSS_GAME_PLAYERS_GAMES1`
    FOREIGN KEY (`gp_PLAYERS_id` , `gp_GAMES_id`)
    REFERENCES `dausdb`.`GAMES_PLAYERS` (`PLAYERS_id` , `GAMES_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
